// <auto-generated />
using System;
using App04.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App04.Services.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20181127091328_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App04.Models.FillUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("JobId");

                    b.Property<double>("Liters");

                    b.Property<int?>("NextId");

                    b.Property<int>("Odometer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("NextId");

                    b.ToTable("FillUp");
                });

            modelBuilder.Entity("App04.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("DriverName");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(250);

                    b.Property<string>("ToLocation")
                        .HasMaxLength(250);

                    b.Property<string>("TruckPlateNo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TruckPlateNo");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("App04.Models.Truck", b =>
                {
                    b.Property<string>("PlateNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<string>("Make")
                        .HasMaxLength(50);

                    b.HasKey("PlateNo");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("App04.Models.FillUp", b =>
                {
                    b.HasOne("App04.Models.Job")
                        .WithMany("FillUps")
                        .HasForeignKey("JobId");

                    b.HasOne("App04.Models.FillUp", "Next")
                        .WithMany()
                        .HasForeignKey("NextId");
                });

            modelBuilder.Entity("App04.Models.Job", b =>
                {
                    b.HasOne("App04.Models.Truck", "Truck")
                        .WithMany("Jobs")
                        .HasForeignKey("TruckPlateNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
